version: '2'
volumes:
  mysql-data:
    driver: convoy
  nc-apps;
    driver: convoy
  nc-config:
    driver: convoy
  nc-data:
    driver: convoy
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
  app:
    image: nextcloud:11-fpm
    links:
      - db
    volumes:
      - nc-apps:/var/www/html/apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  cron:
    image: nextcloud:11-fpm
    links:
      - db
    volumes_from:
      - app
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        /usr/local/bin/php /var/www/html/cron.php
        sleep 900
      done
      EOF'
