version: '2'
services:
  web:
    image: tfenby/nginx-nextcloud
    volumes:
      - /docker/nc/nc-apps:/var/www/html/apps
      - /docker/nc/nc-config:/var/www/html/config
      - /docker/nc/nc-data:/var/www/html/data
      - /docker/nc/nc-www:/var/www/html
  app:
    image: nextcloud:11-fpm
    volumes:
      - /docker/nc/nc-apps:/var/www/html/apps
      - /docker/nc/nc-config:/var/www/html/config
      - /docker/nc/nc-data:/var/www/html/data
      - /docker/nc/nc-www:/var/www/html
    environment:
      NC_FQDN: ${FQDN}
  db:
    image: mysql
    volumes:
      - /docker/nc/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
  cron:
    image: nextcloud:11-fpm
    volumes:
      - /docker/nc/nc-apps:/var/www/html/apps
      - /docker/nc/nc-config:/var/www/html/config
      - /docker/nc/nc-data:/var/www/html/data
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        /usr/local/bin/php /var/www/html/cron.php
        sleep 900
      done
      EOF'
